import { db } from '@/db';
import { productOffer } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Electronics (8 products)
        {
            productName: 'Dell XPS 15 Laptop - 16GB RAM, 512GB SSD',
            description: 'High-performance laptop with Intel Core i7 processor, 15.6" 4K display, perfect for professionals and content creators. Like new condition, includes original charger and box.',
            keyword: 'Dell, laptop, XPS, gaming, work, 4K display',
            shippingType: 'free',
            dateExpiration: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 3,
            price: 1299.99,
            sellerId: 1,
        },
        {
            productName: 'iPhone 14 Pro 256GB - Space Black',
            description: 'Unlocked iPhone 14 Pro with 256GB storage. Excellent condition, minimal wear. Includes original box, cable, and unused earbuds. Battery health at 98%.',
            keyword: 'iPhone, Apple, smartphone, unlocked, 5G',
            shippingType: 'express',
            dateExpiration: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 899.99,
            sellerId: 2,
        },
        {
            productName: 'Sony WH-1000XM5 Noise Cancelling Headphones',
            description: 'Premium wireless headphones with industry-leading noise cancellation. 30-hour battery life, exceptional sound quality. Used for 3 months, like new condition with all accessories.',
            keyword: 'Sony, headphones, wireless, noise cancelling, bluetooth',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 2,
            price: 329.99,
            sellerId: 3,
        },
        {
            productName: 'Canon EOS R6 Mirrorless Camera Body',
            description: 'Professional full-frame mirrorless camera with 20MP sensor and 4K video. Shutter count under 5000. Perfect for photographers upgrading their gear. Includes 2 batteries and charger.',
            keyword: 'Canon, camera, mirrorless, photography, full frame, 4K',
            shippingType: 'express',
            dateExpiration: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 1899.99,
            sellerId: 4,
        },
        {
            productName: 'PlayStation 5 Console - Disc Edition',
            description: 'Sony PS5 with disc drive, includes original controller and all cables. Console in pristine condition, barely used. No games included. Ships in original packaging.',
            keyword: 'PS5, PlayStation, gaming console, Sony, video games',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 2,
            price: 499.99,
            sellerId: 5,
        },
        {
            productName: 'Samsung 65" QLED 4K Smart TV',
            description: 'Stunning 65-inch QLED TV with quantum dot technology, 4K resolution, and smart features. Only 6 months old, excellent condition. Local pickup preferred due to size.',
            keyword: 'Samsung, TV, QLED, 4K, smart TV, television',
            shippingType: 'local pickup',
            dateExpiration: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 1199.99,
            sellerId: 6,
        },
        {
            productName: 'Apple AirPods Pro 2nd Generation',
            description: 'Brand new sealed AirPods Pro with active noise cancellation and spatial audio. Includes MagSafe charging case. Perfect gift or personal upgrade.',
            keyword: 'Apple, AirPods, wireless earbuds, noise cancelling, bluetooth',
            shippingType: 'free',
            dateExpiration: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 5,
            price: 229.99,
            sellerId: 7,
        },
        {
            productName: 'Nintendo Switch OLED - Neon Red/Blue',
            description: 'Latest Switch model with vibrant OLED screen and enhanced audio. Comes with dock, Joy-Cons, and straps. Barely used, like new condition.',
            keyword: 'Nintendo, Switch, gaming, OLED, portable console',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 3,
            price: 349.99,
            sellerId: 8,
        },
        // Fashion (8 products)
        {
            productName: 'Nike Air Jordan 1 Retro High - Size 10',
            description: 'Classic Air Jordan 1 in iconic Chicago colorway. Gently worn, excellent condition with minimal creasing. Original box included. Authentic with receipt.',
            keyword: 'Nike, Jordan, sneakers, shoes, basketball, retro',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 189.99,
            sellerId: 9,
        },
        {
            productName: 'Canada Goose Expedition Parka - Men\'s Large',
            description: 'Authentic Canada Goose parka in black, size Large. Rated for extreme cold. Worn one season, professionally cleaned. Perfect for harsh winters. Includes tags and care card.',
            keyword: 'Canada Goose, jacket, parka, winter coat, mens fashion',
            shippingType: 'free',
            dateExpiration: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 699.99,
            sellerId: 10,
        },
        {
            productName: 'Rolex Submariner Homage Watch - Automatic',
            description: 'High-quality automatic watch with Submariner styling. Sapphire crystal, stainless steel case, 200m water resistance. Excellent craftsmanship, keeps accurate time.',
            keyword: 'watch, automatic, dive watch, mens accessories, stainless steel',
            shippingType: 'express',
            dateExpiration: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 2,
            price: 249.99,
            sellerId: 1,
        },
        {
            productName: 'Louis Vuitton Neverfull MM Tote - Monogram',
            description: 'Authentic LV Neverfull tote in classic monogram canvas. Interior in great condition, minimal wear on handles. Comes with dust bag and authenticity card.',
            keyword: 'Louis Vuitton, handbag, tote, designer, luxury, authentic',
            shippingType: 'express',
            dateExpiration: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 799.99,
            sellerId: 2,
        },
        {
            productName: 'Ray-Ban Aviator Classic Sunglasses - Gold Frame',
            description: 'Iconic aviator sunglasses with gold frame and green lenses. Unisex style, includes original case and cleaning cloth. Barely worn, no scratches on lenses.',
            keyword: 'Ray-Ban, sunglasses, aviator, designer, UV protection',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 3,
            price: 149.99,
            sellerId: 3,
        },
        {
            productName: 'Levi\'s 501 Original Fit Jeans - Multiple Sizes',
            description: 'Classic Levi\'s 501 jeans in dark wash. Available in sizes 30-36 waist. Brand new with tags. Timeless style that never goes out of fashion.',
            keyword: 'Levis, jeans, denim, mens fashion, 501, classic',
            shippingType: 'free',
            dateExpiration: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 15,
            price: 69.99,
            sellerId: 4,
        },
        {
            productName: 'Adidas Ultraboost 22 Running Shoes - Women\'s 8',
            description: 'Premium running shoes with Boost cushioning technology. Women\'s size 8, worn twice on treadmill. Like new condition with original box and extra laces.',
            keyword: 'Adidas, running shoes, Ultraboost, womens shoes, athletic',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 159.99,
            sellerId: 5,
        },
        {
            productName: 'The North Face Denali Fleece Jacket - Black',
            description: 'Classic North Face fleece in black, size Medium. Warm, comfortable, and durable. Gently used with no stains or tears. Perfect for layering or casual wear.',
            keyword: 'North Face, fleece, jacket, outdoor, hiking, camping',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 2,
            price: 89.99,
            sellerId: 6,
        },
        // Toys (7 products)
        {
            productName: 'LEGO Star Wars Millennium Falcon Set 75192',
            description: 'Ultimate Collector Series Millennium Falcon with 7541 pieces. Brand new, sealed in box. Most detailed LEGO Star Wars set ever made. Perfect for display or building.',
            keyword: 'LEGO, Star Wars, Millennium Falcon, collectible, building set',
            shippingType: 'free',
            dateExpiration: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 849.99,
            sellerId: 7,
        },
        {
            productName: 'Hot Toys Iron Man Mark 50 1/6 Scale Figure',
            description: 'Premium collectible figure from Avengers: Infinity War. Highly detailed with over 30 points of articulation. Brand new in sealed box with brown shipper.',
            keyword: 'Hot Toys, Iron Man, action figure, Marvel, collectible',
            shippingType: 'express',
            dateExpiration: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 429.99,
            sellerId: 8,
        },
        {
            productName: 'Catan Board Game - 5th Edition',
            description: 'Award-winning strategy board game for 3-4 players. Includes all pieces and instruction manual. Played a few times, components in excellent condition.',
            keyword: 'Catan, board game, strategy game, family game, settlers',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 19 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 4,
            price: 39.99,
            sellerId: 9,
        },
        {
            productName: 'American Girl Doll - Samantha with Accessories',
            description: 'Retired Samantha doll in excellent condition with original outfit. Includes three additional outfits, accessories, and books. Hair in great shape, face paint perfect.',
            keyword: 'American Girl, doll, Samantha, collectible, vintage toys',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 179.99,
            sellerId: 10,
        },
        {
            productName: 'Traxxas Slash 4x4 RC Truck - Brushless',
            description: 'High-performance 4WD RC truck with brushless motor. Includes battery and charger. Barely used, runs perfectly. Great for off-road racing and bashing.',
            keyword: 'RC car, Traxxas, remote control, truck, hobby, 4x4',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 349.99,
            sellerId: 1,
        },
        {
            productName: 'Pokemon Card Collection - 200+ Cards Lot',
            description: 'Mixed Pokemon card lot with over 200 cards including holos and rares. Various sets from different eras. Great starter collection or trade material.',
            keyword: 'Pokemon, trading cards, collectible, TCG, cards, lot',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 89.99,
            sellerId: 2,
        },
        {
            productName: 'Nerf Ultra One Motorized Blaster',
            description: 'High-capacity Nerf blaster with motorized firing. Includes 25 Nerf Ultra darts. Battery operated, works perfectly. Great for Nerf battles and outdoor fun.',
            keyword: 'Nerf, blaster, toy gun, motorized, outdoor toy',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 3,
            price: 49.99,
            sellerId: 3,
        },
        // Sports (7 products)
        {
            productName: 'Trek Domane SL 5 Road Bike - 56cm',
            description: 'Carbon frame road bike with Shimano 105 groupset. 56cm frame size, barely ridden 100 miles. Perfect condition, professionally maintained. Includes pedals and bottle cages.',
            keyword: 'Trek, road bike, cycling, carbon, Shimano 105',
            shippingType: 'local pickup',
            dateExpiration: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 2299.99,
            sellerId: 4,
        },
        {
            productName: 'Bowflex SelectTech 552 Adjustable Dumbbells',
            description: 'Space-saving adjustable dumbbells, 5-52.5 lbs per dumbbell. Replace 15 sets of weights. Like new condition, barely used. Perfect for home gym setup.',
            keyword: 'Bowflex, dumbbells, weights, home gym, fitness equipment',
            shippingType: 'free',
            dateExpiration: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 2,
            price: 349.99,
            sellerId: 5,
        },
        {
            productName: 'Wilson Pro Staff 97 Tennis Racket',
            description: 'Professional-grade tennis racket, 4 3/8 grip size. Used for one season, strings still in good tension. Includes original case. Perfect for intermediate to advanced players.',
            keyword: 'Wilson, tennis racket, sports equipment, tennis, Pro Staff',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 189.99,
            sellerId: 6,
        },
        {
            productName: 'Yeti Tundra 45 Hard Cooler',
            description: 'Premium rotomolded cooler, holds ice for days. 45-quart capacity, bear-resistant. Excellent condition with minor scratches. Perfect for camping, fishing, tailgating.',
            keyword: 'Yeti, cooler, camping, outdoor, fishing, bear resistant',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 299.99,
            sellerId: 7,
        },
        {
            productName: 'Garmin Forerunner 955 GPS Running Watch',
            description: 'Advanced running watch with built-in GPS, heart rate monitor, and training metrics. 6 months old, scratch-free screen. Includes original box and charger.',
            keyword: 'Garmin, running watch, GPS, fitness tracker, smartwatch',
            shippingType: 'express',
            dateExpiration: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 449.99,
            sellerId: 8,
        },
        {
            productName: 'Callaway Rogue ST Max Driver - 10.5 Stiff',
            description: 'High-performance golf driver with AI-designed jailbreak system. 10.5 degree loft, stiff flex shaft. Used for half season, headcover included. Excellent distance and forgiveness.',
            keyword: 'Callaway, golf driver, golf club, sports equipment, Rogue',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 399.99,
            sellerId: 9,
        },
        {
            productName: 'REI Co-op Quarter Dome SL 2 Tent',
            description: 'Ultralight 2-person backpacking tent weighing only 2 lbs 9 oz. Used on 3 trips, no tears or damage. Includes footprint, stakes, and stuff sack. Easy setup.',
            keyword: 'REI, tent, camping, backpacking, ultralight, 2 person',
            shippingType: 'standard',
            dateExpiration: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
            quantity: 1,
            price: 279.99,
            sellerId: 10,
        },
    ];

    await db.insert(productOffer).values(sampleProducts);
    
    console.log('✅ ProductOffer seeder completed successfully - 30 products added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});