import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const now = new Date();
    const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    const getRandomDate = (start: Date, end: Date) => {
        return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
    };
    
    const getRandomSellerId = () => Math.floor(Math.random() * 8) + 1;
    const getRandomViews = () => Math.floor(Math.random() * 351) + 50;
    const getFutureDate = () => {
        const days = Math.floor(Math.random() * 7) + 1;
        return new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
    };

    const fashionProducts = [
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: "Gucci Women's Floral Dress",
            description: "Size M, silk blend, designer evening dress with floral print. Perfect for special occasions.",
            price: 450.00,
            buyNowPrice: 585.00,
            condition: 'new',
            shippingCost: 15.00,
            imageUrl: '/images/products/gucci-floral-dress.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: "Levi's 501 Original Jeans",
            description: "Men's 32x32, classic blue denim, authentic vintage look with minimal wear. Iconic straight fit.",
            price: 45.00,
            buyNowPrice: 58.50,
            condition: 'used',
            shippingCost: 8.00,
            imageUrl: '/images/products/levis-501-jeans.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Nike Air Max 270 Sneakers',
            description: "Women's Size 8, white/pink colorway, athletic lifestyle shoes with cushioned comfort and modern design.",
            price: 120.00,
            buyNowPrice: 156.00,
            condition: 'new',
            shippingCost: 10.00,
            imageUrl: '/images/products/nike-air-max-270.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Ray-Ban Aviator Sunglasses',
            description: 'Classic gold frame, polarized lenses with UV protection. Iconic style that never goes out of fashion.',
            price: 165.00,
            buyNowPrice: 214.50,
            condition: 'new',
            shippingCost: 5.00,
            imageUrl: '/images/products/rayban-aviator.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Michael Kors Jet Set Tote',
            description: 'Brown leather designer handbag with gold hardware. Spacious interior with multiple pockets.',
            price: 180.00,
            buyNowPrice: 234.00,
            condition: 'used',
            shippingCost: 12.00,
            imageUrl: '/images/products/michael-kors-tote.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Timberland Premium Boots',
            description: "Men's Size 10, wheat nubuck, waterproof construction boots. Classic design with durable build.",
            price: 190.00,
            buyNowPrice: 247.00,
            condition: 'new',
            shippingCost: 10.00,
            imageUrl: '/images/products/timberland-boots.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Versace Silk Tie',
            description: '100% Italian silk designer neckwear with Medusa logo. Elegant pattern for formal occasions.',
            price: 95.00,
            buyNowPrice: 123.50,
            condition: 'new',
            shippingCost: 5.00,
            imageUrl: '/images/products/versace-tie.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Zara Leather Jacket',
            description: "Women's M, black genuine leather biker style with zipper details. Edgy and versatile piece.",
            price: 120.00,
            buyNowPrice: 156.00,
            condition: 'used',
            shippingCost: 12.00,
            imageUrl: '/images/products/zara-leather-jacket.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Rolex Submariner Watch Replica',
            description: 'Stainless steel luxury style timepiece. High-quality replica with accurate details.',
            price: 250.00,
            buyNowPrice: 325.00,
            condition: 'used',
            shippingCost: 8.00,
            imageUrl: '/images/products/rolex-submariner-replica.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 8,
            sellerId: getRandomSellerId(),
            title: 'Burberry Cashmere Scarf',
            description: '100% cashmere winter accessory with classic check pattern. Luxuriously soft and warm.',
            price: 320.00,
            buyNowPrice: 416.00,
            condition: 'new',
            shippingCost: 10.00,
            imageUrl: '/images/products/burberry-scarf.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
    ];

    const toysProducts = [
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'LEGO Star Wars Millennium Falcon',
            description: '7541 pieces ultimate collector series, age 16+. New sealed in box. Detailed replica of iconic ship.',
            price: 799.00,
            buyNowPrice: 1038.70,
            condition: 'new',
            shippingCost: 25.00,
            imageUrl: '/images/products/lego-millennium-falcon.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Barbie Dreamhouse Playset',
            description: '3 stories with elevator, includes furniture and accessories. Age 3+. Interactive features throughout.',
            price: 180.00,
            buyNowPrice: 234.00,
            condition: 'new',
            shippingCost: 15.00,
            imageUrl: '/images/products/barbie-dreamhouse.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Hot Wheels Ultimate Garage',
            description: 'Playset with loops and shark, stores 140+ cars. Age 5+. Multi-level parking and stunts.',
            price: 85.00,
            buyNowPrice: 110.50,
            condition: 'used',
            shippingCost: 12.00,
            imageUrl: '/images/products/hotwheels-garage.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Monopoly Ultimate Banking Edition',
            description: 'Electronic banking game, modern twist on classic. Age 8+. New sealed box.',
            price: 28.00,
            buyNowPrice: 36.40,
            condition: 'new',
            shippingCost: 8.00,
            imageUrl: '/images/products/monopoly-banking.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Nerf Ultra One Motorized Blaster',
            description: '25-dart drum, farthest flying Nerf darts. Age 8+. High-performance foam blaster.',
            price: 45.00,
            buyNowPrice: 58.50,
            condition: 'new',
            shippingCost: 10.00,
            imageUrl: '/images/products/nerf-ultra-one.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Baby Yoda Animatronic Figure',
            description: 'The Child from Mandalorian, 25+ sound effects. Age 4+. New sealed. Interactive toy with movements.',
            price: 55.00,
            buyNowPrice: 71.50,
            condition: 'new',
            shippingCost: 8.00,
            imageUrl: '/images/products/baby-yoda-figure.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: "Rubik's Cube 3x3 Speed Cube",
            description: 'Pro tournament edition with smooth turning. Age 8+. Perfect for speedcubing enthusiasts.',
            price: 18.00,
            buyNowPrice: 23.40,
            condition: 'new',
            shippingCost: 5.00,
            imageUrl: '/images/products/rubiks-cube.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Remote Control Monster Truck',
            description: '4WD off-road vehicle, 1:10 scale with rechargeable battery. Age 8+. High-speed performance.',
            price: 65.00,
            buyNowPrice: 84.50,
            condition: 'used',
            shippingCost: 10.00,
            imageUrl: '/images/products/rc-monster-truck.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Melissa & Doug Wooden Puzzle Set',
            description: '4-pack animal puzzles, educational toy for toddlers. Age 2+. Develops motor skills and problem-solving.',
            price: 32.00,
            buyNowPrice: 41.60,
            condition: 'new',
            shippingCost: 8.00,
            imageUrl: '/images/products/wooden-puzzle-set.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 9,
            sellerId: getRandomSellerId(),
            title: 'Marvel Legends Spider-Man Figure',
            description: 'Collector edition 12", highly detailed with accessories. Age 4+. New sealed premium collectible.',
            price: 42.00,
            buyNowPrice: 54.60,
            condition: 'new',
            shippingCost: 8.00,
            imageUrl: '/images/products/spiderman-figure.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
    ];

    const sportsProducts = [
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Peloton Bike Essentials Package',
            description: 'Indoor cycling bike, includes shoes and weights. Premium home fitness with live classes.',
            price: 1200.00,
            buyNowPrice: 1560.00,
            condition: 'used',
            shippingCost: 0.00,
            imageUrl: '/images/products/peloton-bike.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Wilson Evolution Basketball',
            description: 'Official size 29.5", indoor game ball used by NCAA. Superior grip and feel.',
            price: 65.00,
            buyNowPrice: 84.50,
            condition: 'new',
            shippingCost: 10.00,
            imageUrl: '/images/products/wilson-evolution-basketball.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Spalding NBA Street Basketball',
            description: 'Outdoor composite leather, all-surface performance. Durable for street play.',
            price: 25.00,
            buyNowPrice: 32.50,
            condition: 'used',
            shippingCost: 8.00,
            imageUrl: '/images/products/spalding-street-basketball.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'TRX Training Suspension Straps',
            description: 'Complete home gym kit, includes door anchor and guide. Portable workout system for full-body training.',
            price: 140.00,
            buyNowPrice: 182.00,
            condition: 'new',
            shippingCost: 10.00,
            imageUrl: '/images/products/trx-suspension-straps.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Yeti Tundra 45 Cooler',
            description: '45-quart capacity, bear-resistant outdoor cooler for camping. Keeps ice for days.',
            price: 280.00,
            buyNowPrice: 364.00,
            condition: 'used',
            shippingCost: 15.00,
            imageUrl: '/images/products/yeti-tundra-cooler.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Trek Mountain Bike Marlin 7',
            description: '29" wheels, aluminum frame 21-speed. Great trail bike for all terrains.',
            price: 650.00,
            buyNowPrice: 845.00,
            condition: 'used',
            shippingCost: 0.00,
            imageUrl: '/images/products/trek-marlin-7.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Adidas Predator Soccer Cleats',
            description: "Men's Size 10, firm ground football boots with rubber studs. Enhanced ball control and precision.",
            price: 180.00,
            buyNowPrice: 234.00,
            condition: 'new',
            shippingCost: 10.00,
            imageUrl: '/images/products/adidas-predator-cleats.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Nike Pro Basketball Jersey Lakers',
            description: 'LeBron James #23, authentic NBA swingman jersey size L. Official team colors and design.',
            price: 95.00,
            buyNowPrice: 123.50,
            condition: 'new',
            shippingCost: 8.00,
            imageUrl: '/images/products/lakers-jersey-lebron.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Fitbit Charge 5 Fitness Tracker',
            description: 'Advanced health tracking with GPS and heart rate monitor. OLED display. New sealed.',
            price: 130.00,
            buyNowPrice: 169.00,
            condition: 'new',
            shippingCost: 5.00,
            imageUrl: '/images/products/fitbit-charge-5.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Manduka PRO Yoga Mat',
            description: '6mm thick premium mat, non-slip surface for hot yoga. Eco-friendly and durable.',
            price: 85.00,
            buyNowPrice: 110.50,
            condition: 'used',
            shippingCost: 10.00,
            imageUrl: '/images/products/manduka-yoga-mat.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Rawlings Baseball Glove Heart of the Hide',
            description: '11.5" infield glove, professional grade leather. Game-ready with excellent pocket depth.',
            price: 220.00,
            buyNowPrice: 286.00,
            condition: 'used',
            shippingCost: 10.00,
            imageUrl: '/images/products/rawlings-baseball-glove.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
        {
            categoryId: 10,
            sellerId: getRandomSellerId(),
            title: 'Schwinn IC4 Indoor Cycling Bike',
            description: 'Bluetooth connectivity, magnetic resistance with LCD monitor. Refurbished with warranty.',
            price: 650.00,
            buyNowPrice: 845.00,
            condition: 'refurbished',
            shippingCost: 0.00,
            imageUrl: '/images/products/schwinn-ic4-bike.jpg',
            status: 'active',
            views: getRandomViews(),
            createdAt: getRandomDate(thirtyDaysAgo, now).toISOString(),
            endsAt: getFutureDate(),
        },
    ];

    const allProducts = [...fashionProducts, ...toysProducts, ...sportsProducts];

    await db.insert(products).values(allProducts);
    
    console.log('✅ Products seeder completed successfully - Added 32 new products (10 fashion, 10 toys, 12 sports)');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});